
sources:
  # VERTS (OK robots/sitemaps) – intégration douce
  - name: Laforet971
    type: sitemap
    enabled: true
    base_url: "https://www.laforet.com/"
    sitemap: "https://www.laforet.com/sitemap-annonces.xml"

  - name: Orpi971
    type: sitemap
    enabled: true
    base_url: "https://www.orpi.com/"
    sitemap: "https://www.orpi.com/sitemap.xml"

  # JAUNES (listings publics autorisés) – activés progressivement
  - name: BienIci
    type: html
    enabled: false
    base_url: "https://www.bienici.com/"

  - name: LogicImmo
    type: html
    enabled: false
    base_url: "https://www.logic-immo.com/"

  - name: Domimmo
    type: html
    enabled: false
    base_url: "https://www.domimmo.com/"

  # AGENCES LOCALES (listings publics / pages annonces) — VERTS
  - name: AgencesLocales
    type: html
    enabled: true
    base_urls:
      - "https://www.immo971.com/"
      - "https://www.immovital.com/"
      - "https://www.karukimo.fr/"
      - "https://www.ocea-immobilier.fr/"
      - "https://www.desflots-immobilier.com/"
      - "https://www.benedicimmo971.com/"
    note: "Listings publics / pages 'vente', 'nos-biens', 'annonces' — conformité robots."
